### ISSUE TITLE
Putting entire CLDF dataset in a subdirectory, then accessing commands?

### ISSUE THREAD

**Issue by shanest** [cldf-datasets/steinertthrelkeldmodals#2]
Hi Robert,

Thanks again for all your help with this!  We are getting ready to release a public version of this database, but are running into a small issue that's tough to debug.  In particular, we want one repo with two main directory: `basic-format` (a kind of "raw" data) and a `cldf-format`.  The latter directory basically has a copy of this repo, with some small revisions that have been made as we've developed the dataset further.  There are then some extra scripts to move relevant data from `basic-format` to `cldf-format/raw` so that the CLDF version can be built.  

Everything seems to work, but when running `cldfbench makecldf cldfbench_modals.py`, I get the following errors:
```
~/anaconda3/envs/typ-test/lib/python3.10/site-packages/clldutils/clilib.py:234: UserWarning: No module named 'cldfbench_steinertthrelkeldmodals' modalscommands.iff
  warnings.warn('{0} {1}'.format(e, modname))
WARNING Error importing modals: No module named 'cldfbench_steinertthrelkeldmodals'
```

And the `modals.iff` entry point seems not to work as well; when running `cldfbench modals.iff`, I get `~/anaconda3/envs/typ-test/lib/python3.10/site-packages/clldutils/clilib.py:234: UserWarning: No module named 'cldfbench_steinertthrelkeldmodals' modalscommands.iff`.

I'm sure that this is something about python package installation and sub-directories that's just over my head, but I was wondering if there's an easy fix here for putting this entire CLDF structure in a sub-directory of a repo, and still leveraging all of the benefits of the commands interface and whatnot.  Thanks again!

**Comment by shanest** [comment]
Nevermind, resolved :)

**Comment by xrotwang** [comment]
Ah, good! Couldn't reproduce :)
